"""Collection_objects incedent

Revision ID: 8c8156163c27
Revises: 371437e41c6c
Create Date: 2025-05-15 17:58:50.034899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c8156163c27'
down_revision: Union[str, None] = '371437e41c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_clients_id', table_name='clients')
    op.add_column('collection_objects', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('collections', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_collections_id', table_name='collections')
    op.drop_index('ix_genres_id', table_name='genres')
    op.drop_index('ix_objects_id', table_name='objects')
    op.alter_column('ratings', 'rated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'rated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_objects_id', 'objects', ['id'], unique=False)
    op.create_index('ix_genres_id', 'genres', ['id'], unique=False)
    op.create_index('ix_collections_id', 'collections', ['id'], unique=False)
    op.alter_column('collections', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collections', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('collection_objects', 'created_at')
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.alter_column('clients', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
